### ISSUE TITLE
Brightness Keys and Fn Keys

### ISSUE THREAD

**Issue by lekoOwO** [Parthvsquare/Opencore-LG-gram-14z980#1]
Hello. Thanks for your hard working!

Though I followed the [Tutorial](https://github.com/suzuke/LG-Gram-13z980-Opencore), Installed and launched LGGramAssistant (The SSDT-FNKey.aml is included in your repo, also tried replace w/ his), the Brightness key and some Fn Keys are not working.

Can you share how you make it work? Thanks!

BTW I'm using 14Z980 too.

**Comment by Parthvsquare** [comment]
It worked on catalina, later it stopped working after big sur for me too. If you find any hacks do let me know.

**Comment by lekoOwO** [comment]
I've found that https://github.com/acidanthera/BrightnessKeys works well
