### ISSUE TITLE
Trackpad Issue

### ISSUE THREAD

**Issue by lekoOwO** [Parthvsquare/Opencore-LG-gram-14z980#2]
Hello.

After my 14z980 slept, the trackpad never worked again in macOS (normal in Windows), even if I reboot, clear NVRAM or boot into recovery.
Did you ever met this issue? Thanks!

**Comment by Parthvsquare** [comment]
Nope never have i encountered such issue. Try following this guide [optimizing power management](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#enabling-x86platformplugin) and go through the post install section

**Comment by lekoOwO** [comment]
Hmm after several time reboot the trackpad works again. Seems like a random bug.
